language: python
python:
  - "3.6"
install:
  - pip install python-coveralls
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: nosetests --verbosity=3 --with-cov --cover-erase --cover-package=flightradar24 tests

after_success:
  coveralls
