language: python
python:
  - "3.6"
install:
  - python setup.py install
  - pip install coverage coveralls
# command to run tests
script: nosetests -v --with-coverage --cover-tests --cover-package=flightradar24 tests

after_success:
  coveralls
